# Site settings
title: Amherst Electronics Club
email: amherstec@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Founded in the spring of 2012, the Amherst College Electronics Club 
  provides an opportunity for students to learn about embedded electronics and 
  develop team projects. We designed a simple robot in the beginning of 2013, we 
  launched Project Daedalus, built LED cubes, and hopefully many other projects will come to life through the club.
baseurl: "/blog" # the subpath of your site, e.g. /blog/
url: "http://amherstec.github.io/" # the base hostname & protocol for your site
twitter_username: amherstec
github_username:  amherstec

# Build settings
markdown: kramdown
